### ISSUE TITLE
Specify minimum Node version

### ISSUE THREAD

**Issue by dominicfraser** [cyco130/detype#1]
Hi 👋 

Thanks for making a great tool. 

I've been testing this as a way to reassure stakeholders that using TS is an easy change to back out of. While testing I found that the minimum Node version appears to be Node 16. The project I am working in uses Node 12, and I initially wasn't sure why the package was failing. It was simple to change Node versions just for the tool using `nvm`, but it would be great if the README could specify this :) 

Thanks again!

**Comment by cyco130** [comment]
Hello,

Thanks for the heads up. Solved and documented in (just released) 0.3.3. It now supports Node 14 too. ~~Node 12 is not maintained anymore, so I don't want to support it.~~ (not true, [see below](https://github.com/cyco130/detype/issues/1#issuecomment-953541418))

**Comment by dominicfraser** [comment]
🚀 Perfect, thanks!

**Comment by cyco130** [comment]
I was confused about Node 12 not being maintained, it's still maintained and supported as of 0.3.4.
