### ISSUE TITLE
Discussion: Move type info to jsdoc comments

### ISSUE THREAD

**Issue by tw1nk** [cyco130/detype#12]
It would be great if this could move the type info to jsdoc comments instead of removing it.

**Comment by cyco130** [comment]
This is obviously a great idea and it would be a very valuable tool. But it would require a complete rewrite:

Currently, `detype` is using Babel plus some formatting tricks to remove the types. Babel doesn't understand types, it only recognizes the syntax, enough to simply remove them.

Turning TypeScript annotations into jsdoc comments would probably require actually understanding the types. I'm guessing that would require something built on TypeScript. As such, it's out of scope for me.

Besides, the very fact that no such tool exists despite a lot of Twitter drama on the relative merits of jsdoc vs TS, I'm inclined to think that it's easier said than done.
