### ISSUE TITLE
[Windows] CLI not generating files when <INPUT> is a directory

### ISSUE THREAD

**Issue by jrson83** [cyco130/detype#3]
When using  Windows (I used windows 11) and running the CLI with a specified directory as `<INPUT>`, the specified `<OUTPUT>` directory is generated but empty. So no files are processed at all, it just creates an empty output directory.

**Comment by cyco130** [comment]
I set up a CI workflow to try to fix this. I _think_ it should be fixed on `0.5.0` but I can't be sure since I don't have access to a Windows machine at the moment. Please check if it's been solved for you.

**Comment by jrson83** [comment]
> I set up a CI workflow to try to fix this. I _think_ it should be fixed on `0.5.0` but I can't be sure since I don't have access to a Windows machine at the moment. Please check if it's been solved for you.

I tested `0.5.0` on Windows 11 and it is fully working now. It generates folders & subfolders and generates the `.jsx` files. Thank you!
