### ISSUE TITLE
`TypeError: compiler.parse is not a function` happens when transforming vue files

### ISSUE THREAD

**Issue by sapphi-red** [cyco130/detype#6]
Reproduction: https://stackblitz.com/edit/node-gmj99t?file=package.json

https://github.com/cyco130/detype/blob/02b7cca52382603927e8089d97b1a67aaf6bafed/src/transform.ts#L55
https://github.com/vuedx/languagetools/blob/3108b32d67dc5e010f8e4738126d845af5faac5f/packages/compiler-sfc/src/parse.ts#L31-L45
I guess this is happening is because `{ filename: fileName }` is passed as `compiler` parameter.

**Comment by cyco130** [comment]
Thanks for reporting.

Fixed in `0.6.2`: https://stackblitz.com/edit/node-w53gua

Note to self: Don't use `^` when package version is `0.x.y`.

**Comment by sapphi-red** [comment]
Thanks!
